/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   on_expose.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: abelov <abelov@student.42london.com>       +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/05/25 03:11:20 by abelov            #+#    #+#             */
/*   Updated: 2026/07/10 18:35:31 by abelov           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_fdf.h"

t_rect	get_rect(t_fdf *fdf, t_map_row *row, int cr, int cc);

/**
 * The XSync function flushes the output buffer and then waits until
 * all requests have been received and processed by the X server.
 * Any errors generated must be handled by the error handler.
 * For each protocol error received by Xlib, XSync calls the client
 * application's error handling routine (see section 11.8.2).
 *
 * Any events generated by the server are enqueued into the library's
 * event queue.
 */
void	on_expose(t_fdf *fdf)
{
	t_map_row	*row;
	t_rect		rect;
	int			cr;
	int			cc;

	row = fdf->map;
	cr = fdf->rows;
	while (--cr)
	{
		cc = fdf->cols;
		while (--cc)
		{
			rect = get_rect(fdf, row, cr, cc);
			draw_line_d(fdf, rect.t1, rect.t2);
			draw_line_d(fdf, rect.t1, rect.t3);
			if (cr == 1)
				draw_line_d(fdf, rect.t3, rect.t4);
			if (fdf->custom_colour_flag)
				draw_line_d(fdf, rect.t1, rect.t4);
		}
		draw_line_d(fdf, rect.t2, rect.t4);
		row = row->next;
	}
	mlx_put_image_to_window(fdf->mlx, fdf->root,
		fdf->canvas, fdf->offset.x, fdf->offset.y);
}

t_rect	get_rect(t_fdf *fdf, t_map_row *row, int cr, int cc)
{
	t_rect	rect;

	rect.t1 = get_point(fdf, row, cc, cr);
	rect.t2 = get_point(fdf, row, cc - 1, cr);
	rect.t3 = get_point(fdf, row->next, cc, cr - 1);
	rect.t4 = get_point(fdf, row->next, cc - 1, cr - 1);
	return (rect);
}
